version: '3'
services:
   web:
     image: wiroforce-web
     ports: 
       - 9014:3000
     restart: always
     environment: 
       - NEXTAUTH_URL=https://conwiro.nat.cu/wiroforce
       - NEXT_PUBLIC_API_URL=https://conwiro.nat.cu/wiroforce-api/api/v1
       - API_INTERNAL_URL=http://api:3000/api/v1
       - METABASE_URL=https://conwiro.nat.cu/metabase
     build:
          context: .

networks: 
  default: 
    external: 
      name: wiroforce